const sneakers = [
  {
    id: 1,
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/3cc96f43-47b6-43cb-951d-d8f73bb2f912/air-force-1-07-shoes-WrLlWX.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/3cc96f43-47b6-43cb-951d-d8f73bb2f912/air-force-1-07-shoes-WrLlWX.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Nike Air",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/585e2cd2-4f2a-408c-a8ba-f89952cdf332/revolution-6-next-nature-road-running-shoes-NC0P7k.png",
    quantity: 1,
  },
  {
    id: 4,
    name: "Nike Air ",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/585e2cd2-4f2a-408c-a8ba-f89952cdf332/revolution-6-next-nature-road-running-shoes-NC0P7k.png",
    quantity: 1,
  },
  {
    id: 5,
    name: "Nike sb dunks panda",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://dynamic.zacdn.com/9x7G3RLBkSKi47nMpklQXxvQlb8=/fit-in/346x500/filters:quality(95):fill(ffffff)/https://static-ph.zacdn.com/p/nike-7964-2825281-1.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "baggy sweat pants",
    brand: "Nike",
    category: "pants",
    colorway: "White/White",
    price: 9000,
    image: "https://cf.shopee.ph/file/d2d072fae469b4d8641438d3da70e86a",
    quantity: 1,
  },
  {
    id: 7,
    name: "Black Pants",
    brand: "Nike",
    category: "pants",
    colorway: "White/White",
    price: 9000,
    image:
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450280/sub/goods_450280_sub14.jpg?width=750",
    quantity: 1,
  },
  {
    id: 8,
    name: "Hoodie",
    brand: "Nike",
    category: "Hoodie",
    colorway: "White/White",
    price: 9000,
    image: "https://i.ebayimg.com/images/g/K~8AAOSwTgVhg8sO/s-l400.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Hoodie",
    brand: "Nike",
    category: "Hoodie",
    colorway: "White/White",
    price: 9000,
    image:
      "https://lzd-img-global.slatic.net/g/p/aeaff4091bfd88688ce70eae00481a6a.jpg_720x720q80.jpg_.webp",
    quantity: 1,
  },
  {
    id: 10,
    name: "Nike sb dunks panda",
    brand: "Nike",
    category: "shoes",
    colorway: "White/White",
    price: 9000,
    image:
      "https://dynamic.zacdn.com/9x7G3RLBkSKi47nMpklQXxvQlb8=/fit-in/346x500/filters:quality(95):fill(ffffff)/https://static-ph.zacdn.com/p/nike-7964-2825281-1.jpg",
    quantity: 1,
  },
  {
    id: 11,
    name: "baggy sweat pants",
    brand: "Nike",
    category: "pants",
    colorway: "White/White",
    price: 9000,
    image: "https://cf.shopee.ph/file/d2d072fae469b4d8641438d3da70e86a",
    quantity: 1,
  },
  {
    id: 12,
    name: "Black Pants",
    brand: "Nike",
    category: "pants",
    colorway: "White/White",
    price: 9000,
    image:
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450280/sub/goods_450280_sub14.jpg?width=750",
    quantity: 1,
  },
  {
    id: 13,
    name: "Hoodie",
    brand: "Nike",
    category: "Hoodie",
    colorway: "White/White",
    price: 9000,
    image: "https://i.ebayimg.com/images/g/K~8AAOSwTgVhg8sO/s-l400.jpg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Hoodie",
    brand: "Nike",
    category: "Hoodie",
    colorway: "White/White",
    price: 9000,
    image:
      "https://lzd-img-global.slatic.net/g/p/aeaff4091bfd88688ce70eae00481a6a.jpg_720x720q80.jpg_.webp",
    quantity: 1,
  },
];

export default sneakers;
